### ISSUE TITLE
Convert grid to reflect data 

### ISSUE THREAD

**Issue by lieric4567** [kpack18/kpack18.github.io#45]
Creating a grid using the specified dimensions, storing that information so that it can be used later for algorithms and etc.

Acceptance test:
1) Resizes grid to match width x height entered into form after clicking apply.
2) Can interact with the grid change tile colors on mouse over and click. 
3) Print grid's resulting string represents the current state of the grid.

**Comment by kpack18** [comment]
Test: test_Resize

Resizes the grid to multiple dimensions and check's that the dimensions of the class match the update. (Also tests that only valid dimensions can be added (no negatives, no letters etc..)
