### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by lieric4567** [kpack18/kpack18.github.io#59]
When clicking the reset button reset everything on the grid.

Acceptance test:
1. After clicking the button a prompt appears to confirm a reset.
2. After confirming by pressing yes the grid should be reset, every tile should be cleared.
3. After resetting every tile should be accessible.
4. After resetting all tile functionality should be usable, drawing, algorithm, etc.

**Comment by kpack18** [comment]
test found in tests/clear_grid/test_clearGrid.js

the clear grid tests executes an algorithm on a maze and then clicks the clear grid button for two different mazes including:

1.) One with a linear but complex path
2.) Once filled with 4 different weighted colors
