### ISSUE TITLE
Create Timer

### ISSUE THREAD

**Issue by tadari** [kpack18/kpack18.github.io#65]
Task: Create a timer to see how long any given algorithm takes to find the end point.

Acceptance Test:
1.) Select and run any algorithm.
2.) Upon hitting the "Algorithm" button the timer should start.
3.) The timer should stop when either the end point is reached, no solution is found, or if the "Stop" button is pressed before a result can be found.
4.) The timer should reset upon starting a new algorithm.

**Comment by kpack18** [comment]
test found in tests/statistics/test_statistics

compares the run time of the algorithm to what's displayed in the settings panel on two mazes:

1.) One where the start and end point are the same
2.) A simple linear path maze with a non zero run time
